### PR TITLE
Blazor app

### PR DESCRIPTION
**Pull request by galehouse5**
Created Blazor app with capabilities similar to WPF app. Can be hosted by a simple file server/GitHub Pages with slight modifications to perform client-side URL rewriting. (See this repo for an example of hosting with GitHub Pages: https://ao-ladderer.github.io.) Had to retarget some projects to .NET Standard 2.0. Also removed some deprecated code.

Here are screenshots:

[image](https://ao-ladderer.github.io/build)

[image](https://ao-ladderer.github.io/ladder)

[image](https://ao-ladderer.github.io/shopping)

### CODE REVIEW

**Comment by galehouse5** [comment]
Migrated Blazor app from https://galehouse5.github.io/ao-ladderer to https://ao-ladderer.github.io. Had to create an organization named "ao-ladderer" to unlock the shorter URL through GitHub Pages. Invited you as owner of organization, @davghouse.

**Review by davghouse — CHANGES_REQUESTED** [review]
Wow, cool website, thanks. I've just noticed a few minor things:

I think 'Off' is kind of confusing. I read it at first as the implant is off/unequipped, not the slot is turned off for the ladder process. I guess 'N/A' (meaning not available) is decent while still keeping the label short, and vibes better with the readme which uses the term 'unavailable'. It could still be confusing though. If tooltips are a thing it might be nice to say 'Marks the slot as not available for laddering (already occupied).' I also considered 'Lock', but I feel like it has a bigger chance for confusion than 'N/A'.

Instead of 'Use slow algorithm for slightly better implant QL', maybe something like 'Use advanced algorithm (slower, more laddering, slightly higher average QL)'. I think it's important to point out there will be more ladder implants. Could also do 'Increase laddering depth' with a tooltip like 'Increasing the laddering depth will result in a slightly higher average QL, but will take longer and use more ladder implants'.

'None' at the top confused me a little bit, it looked like it applied to all buffs. As a quick fix could move 'None's to bottoms of their sections.

IC or PS doesn't add correct amount--it's adding 60 Str but should be adding 40.

Instead of 'Final implant average QL', which doesn't seem to read very well, could do 'Average final implant QL'.

**Comment by davghouse** [comment]
Bigger things I noticed but I don't know if it's reasonable/feasible to address them or if they would require a lot of effort:

Performance problems when changing tabs and using advanced algorithm. Ideally we calculate when clicking on the 'Ladder' button and then can change tabs freely after that point. But it seems like there are big slowdowns when changing tabs sometimes, like we have to rerun the ladderer. [example](https://ao-ladderer.github.io/permalink?WyJCaW8uTWV0YW1vciIsIkRpbWFjaCIsIiIsMCwiIiwiIiwiIiwwLCIiLCIiLCIiLDAsIiIsIiIsIiIsMCwiIiwiIiwiIiwwLCIiLCIiLCIiLDAsIiIsIkJvZHkgRGV2IiwiIiwwLCJSYW5nZWQuIEluaXQiLCIiLCIiLDAsIiIsIlJ1biBTcGVlZCIsIiIsMCwiQWdpbGl0eSIsIlN0YW1pbmEiLCIiLDAsIlRyYXAgRGlzYXJtIiwiU2hvdGd1biIsIjFoIEJsdW50IiwwLCIiLCIiLCIiLDAsIiIsIiIsIiIsMCwwLDAsMCwwLDAsMCwwLDEsMSwxLDEsMSwxLDEsMSwxLDIsMV0=)

Tab state doesn't doesn't persist as you switch tabs (you check stuff off but the checks go away when you switch tabs).

**Comment by galehouse5** [comment]
Good suggestions. I made the changes you recommended.

The loss of checked state for ladder/shopping items and poor performance when changing tabs was related and was due to a bug.

I chose to deal with the initial performance hit when building an advanced ladder by displaying a loading indicator so the user knows what's happening. Not much else we can do aside from profiling/tuning `AdvancedLadderProcess` or removing the feature entirely.

Deployed changes to https://ao-ladderer.github.io so you can play around.

**Comment by galehouse5** [comment]
[Performance of code in Blazor is extremely poor (~200x slower than on desktop)](https://github.com/aspnet/Blazor/issues/860)

**Comment by davghouse** [comment]
Thanks for the changes, I really appreciate the loading indicator.

At first I didn't like the use of the word "Sorry" but I tried with full implants and as you said it is actually quite slow and somewhat out of our control. For me it was taking several minutes so you might change "a minute" to "a few minutes" or something.

And the Str and Sta values of IronCircleOrProdigiousStrength need to be swapped.

That's all I see right now that's stopping the merge. There are some other differences in functionality when compared to the desktop version, and I will note them here for completeness. However, I don't care enough to do something about them.

Permalink only includes build tab, but it might be nice if you could permalink to your work in progress (include state of all tabs, and which tab is currently selected).

Changing something on the build tab & then swapping tabs causes the ladder to recompute, which may be somewhat unexpected. The desktop version is a little simpler--ladder only recomputes when I press the button to make it recompute. The only use case I can think of for this is swapping around different clusters to make an implant require a different ability to see if you can get a higher average QL. If you can't find a suitable different cluster to try, you might change it back to the original cluster and then expect the other tabs to be how you left them. As things are right now, recomputation would happen even if the build tas ends up back in its original state. This is bad because performance is bad, not necessarily because I would expect users to have important selections on the other two tabs at this point--they'd probably still be blank during this experimentation.

**Review by davghouse — APPROVED** [review]

**Comment by galehouse5** [comment]
Thanks.

Permalinks are really long right now because I couldn't get `DeflateStream` to work in Blazor/Mono/WASM due to https://github.com/aspnet/Blazor/issues/445. I would like to add all the state to them once they can be compressed.

**Comment by davghouse** [comment]
I added you as a collaborator. You can do any future work here if you want.

(And you can consider deleting your fork if you don't want it cluttering up your profile.
https://www.reddit.com/r/github/comments/3xfi6e/should_i_delete_forks_after_pull_request/
https://softwareengineering.stackexchange.com/questions/61577/should-i-keep-my-github-forked-repositories-around-forever)

**Pull request merged**
